/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import com.jogamp.opengl.awt.GLCanvas;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JOptionPane;
import figures.FIGURE;
import handlers.Renderer;

import java.awt.geom.Dimension2D;
import java.io.File;
import javax.swing.JFileChooser;
import utils.FileChooser;

/**
 *
 * @author nikita
 */
public class FiguresUI extends javax.swing.JFrame {

    /**
     * Creates new form FiguresUI
     */
    public FiguresUI(GLCanvas glcanvas) {/*
        initComponents();
        Dimension sSize = Toolkit.getDefaultToolkit().getScreenSize();
        glcanvas.setSize(sSize);
        this.getContentPane().add(glcanvas);
        this.setVisible(true);*/

        initComponents();
        Dimension sSize = Toolkit.getDefaultToolkit().getScreenSize();
        this.setExtendedState(MAXIMIZED_BOTH);
        glcanvas.setSize(sSize.width - 150, sSize.height);
        this.getContentPane().add(glcanvas);
        this.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        cubeBtn = new javax.swing.JButton();
        selectFigureLabel = new javax.swing.JLabel();
        newSphereBtn = new javax.swing.JButton();
        pyramidBtn = new javax.swing.JButton();
        sphereParamsLabel = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        sphereParams = new javax.swing.JTextField();
        projectorFileBtn = new javax.swing.JButton();
        projectorFile = new javax.swing.JLabel();
        ProjectorSettings = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        configuration = new javax.swing.JRadioButton();
        byHands = new javax.swing.JRadioButton();
        projectorCoords = new javax.swing.JLabel();
        xCoordLabel = new javax.swing.JLabel();
        xCoord = new javax.swing.JFormattedTextField();
        yCoordLabel = new javax.swing.JLabel();
        zCoordLabel = new javax.swing.JLabel();
        yCoord = new javax.swing.JTextField();
        zCoord = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 1000));

        cubeBtn.setText("Куб");
        cubeBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cubeBtnActionPerformed(evt);
            }
        });

        selectFigureLabel.setText("Выберите фигуру");

        newSphereBtn.setText("Новая Сфера");
        newSphereBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newSphereBtnActionPerformed(evt);
            }
        });

        pyramidBtn.setText("Пирамида");
        pyramidBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pyramidBtnActionPerformed(evt);
            }
        });

        sphereParamsLabel.setText("Параметры граней");

        sphereParams.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sphereParamsActionPerformed(evt);
            }
        });

        projectorFileBtn.setText("Выбрать");
        projectorFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectorFileBtnActionPerformed(evt);
            }
        });

        projectorFile.setText("Файл для проектора:");

        ProjectorSettings.setText("Настройки проектора:");

        buttonGroup1.add(configuration);
        configuration.setText("Конфигурация");
        configuration.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                configurationActionPerformed(evt);
            }
        });

        buttonGroup1.add(byHands);
        byHands.setSelected(true);
        byHands.setText("Задать вручную");
        byHands.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                byHandsActionPerformed(evt);
            }
        });

        projectorCoords.setText("Координаты проектора:");

        xCoordLabel.setText("x");

        yCoordLabel.setText("y");

        zCoordLabel.setText("z");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projectorFile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(95, 95, 95))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(configuration)
                            .addComponent(newSphereBtn)
                            .addComponent(sphereParamsLabel)
                            .addComponent(sphereParams, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectFigureLabel)
                            .addComponent(projectorCoords)
                            .addComponent(cubeBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(pyramidBtn)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(zCoordLabel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(zCoord))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(yCoordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(xCoordLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(xCoord, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                                        .addComponent(yCoord))))
                            .addComponent(projectorFileBtn)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(byHands, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ProjectorSettings, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(selectFigureLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cubeBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pyramidBtn)
                .addGap(36, 36, 36)
                .addComponent(sphereParamsLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sphereParams, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(newSphereBtn)
                .addGap(47, 47, 47)
                .addComponent(ProjectorSettings)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(configuration)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel6))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(byHands)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectorCoords)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xCoordLabel)
                    .addComponent(xCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yCoordLabel)
                    .addComponent(yCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zCoordLabel)
                    .addComponent(zCoord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(projectorFile)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(projectorFileBtn)
                .addContainerGap(563, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 613, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cubeBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cubeBtnActionPerformed
        Renderer.figure = FIGURE.CUBE;
    }//GEN-LAST:event_cubeBtnActionPerformed

    private void newSphereBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newSphereBtnActionPerformed
        Renderer.figure = FIGURE.SPHERE;
        String edges = sphereParams.getText();
        int numEdges;
        try {
            numEdges = Integer.parseInt(edges);
            if (numEdges < 2) {
                throw new Exception();
            }
            Renderer.lats = numEdges;
            Renderer.longs = numEdges;
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Введите положительное число");
        }
    }//GEN-LAST:event_newSphereBtnActionPerformed

    private void pyramidBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pyramidBtnActionPerformed
        Renderer.figure = FIGURE.PYRAMID;
    }//GEN-LAST:event_pyramidBtnActionPerformed

    private void sphereParamsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sphereParamsActionPerformed

    }//GEN-LAST:event_sphereParamsActionPerformed

    private void projectorFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectorFileBtnActionPerformed
        boolean isByHands = buttonGroup1.isSelected(byHands.getModel());
        FileChooser chooseFile = new FileChooser();
        if (isByHands) {
            try {
                Renderer.xProjectorCoord = Integer.parseInt(xCoord.getText());
                Renderer.yProjectorCoord = Integer.parseInt(yCoord.getText());
                Renderer.zProjectorCoord = Integer.parseInt(zCoord.getText());

                Renderer.configFile = chooseFile.selectFile();
                    System.out.println(Renderer.configFile);
                
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Введите корректные координаты");
            }
        } else {
            Renderer.projectorFile = chooseFile.selectFile();
        }

    }//GEN-LAST:event_projectorFileBtnActionPerformed

    private void configurationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_configurationActionPerformed
        setVisibleConfig(false);
    }//GEN-LAST:event_configurationActionPerformed

    private void byHandsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_byHandsActionPerformed
        setVisibleConfig(true);
    }//GEN-LAST:event_byHandsActionPerformed

    private void setVisibleConfig(boolean isVisible) {
        projectorCoords.setVisible(isVisible);
        xCoordLabel.setVisible(isVisible);
        yCoordLabel.setVisible(isVisible);
        zCoordLabel.setVisible(isVisible);
        xCoord.setVisible(isVisible);
        yCoord.setVisible(isVisible);
        zCoord.setVisible(isVisible);
        projectorFile.setVisible(isVisible);
        projectorCoords.setVisible(isVisible);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ProjectorSettings;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JRadioButton byHands;
    private javax.swing.JRadioButton configuration;
    private javax.swing.JButton cubeBtn;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton newSphereBtn;
    private javax.swing.JLabel projectorCoords;
    private javax.swing.JLabel projectorFile;
    private javax.swing.JButton projectorFileBtn;
    private javax.swing.JButton pyramidBtn;
    private javax.swing.JLabel selectFigureLabel;
    private javax.swing.JTextField sphereParams;
    private javax.swing.JLabel sphereParamsLabel;
    private javax.swing.JFormattedTextField xCoord;
    private javax.swing.JLabel xCoordLabel;
    private javax.swing.JTextField yCoord;
    private javax.swing.JLabel yCoordLabel;
    private javax.swing.JTextField zCoord;
    private javax.swing.JLabel zCoordLabel;
    // End of variables declaration//GEN-END:variables
}
